# Zsh completion for atip. Generated by "atip completion zsh".
# Sourced automatically by the repo .zshrc; from any other shell, add
# "source /path/to/_completion.zsh" to ~/.zshrc.

# compdef only exists once compsys is initialized; bootstrap it so this file
# can be sourced from a shell that never ran compinit.
if ! (( ${+functions[compdef]} )); then
  autoload -Uz compinit
  compinit -i
fi

_atip_org_slugs() {
  local -a slugs
  slugs=(${(f)"$(atip complete org-slugs 2>/dev/null)"})
  if (( ${#slugs} )); then
    _describe 'institution slug' slugs
  fi
}

_atip_request_refs() {
  local -a refs
  refs=(${(f)"$(atip complete request-refs 2>/dev/null)"})
  if (( ${#refs} )); then
    _describe 'tracked request' refs
  fi
}

_atip_completion() {
  local state line
  typeset -A opt_args

  _arguments -C \
    '1:subcommand:(zsh)' \
    '*:: :->args'

  case $state in
    args)
      case $line[1] in
    zsh) _normal ;;
      esac
      ;;
  esac
}

_atip_informal() {
  _arguments -s -S \
    '1:request-number:' \
    '(-o --org)'{-o,--org}'[org]:org:_atip_org_slugs' \
    '--no-track[no-track]'
}

_atip_login() {
  _arguments -s -S \
    '--paste[paste]' \
    '--check[check]'
}

_atip_orgs() {
  _arguments -s -S \
    '1::pattern:'
}

_atip_portal_open() {
  _arguments -s -S \
    '--url[url]:url:'
}

_atip_portal() {
  local state line
  typeset -A opt_args

  _arguments -C \
    '1:subcommand:(open)' \
    '*:: :->args'

  case $state in
    args)
      case $line[1] in
    open) _atip_portal_open ;;
      esac
      ;;
  esac
}

_atip_request_list() {
  _arguments -s -S \
    '--cached[cached]' \
    '--status[status]:status:(submitted acknowledged in-progress extended records-ready completed abandoned)' \
    '--json[json]' \
    '--raw[raw]'
}

_atip_request_new() {
  _arguments -s -S \
    '(-i --institution)'{-i,--institution}'[institution]:institution:' \
    '(-s --summary)'{-s,--summary}'[summary]:summary:'
}

_atip_request_remove() {
  _arguments -s -S \
    '1:ref:_atip_request_refs'
}

_atip_request_show() {
  _arguments -s -S \
    '1:ref:_atip_request_refs'
}

_atip_request_status() {
  _arguments -s -S \
    '1:ref:_atip_request_refs'
}

_atip_request_update() {
  _arguments -s -S \
    '1:ref:_atip_request_refs' \
    '--status[status]:status:(submitted acknowledged in-progress extended records-ready completed abandoned)' \
    '--number[number]:number:' \
    '--institution[institution]:institution:' \
    '--summary[summary]:summary:' \
    '--note[note]:note:'
}

_atip_request() {
  local state line
  typeset -A opt_args

  _arguments -C \
    '1:subcommand:(list ls new remove show status update)' \
    '*:: :->args'

  case $state in
    args)
      case $line[1] in
    list|ls) _atip_request_list ;;
    new) _atip_request_new ;;
    remove) _atip_request_remove ;;
    show) _atip_request_show ;;
    status) _atip_request_status ;;
    update) _atip_request_update ;;
      esac
      ;;
  esac
}

_atip_search() {
  _arguments -s -S \
    '1::keywords:' \
    '(-o --org)'{-o,--org}'[org]:org:_atip_org_slugs' \
    '(-y --year)'{-y,--year}'[year]:year:' \
    '(-m --month)'{-m,--month}'[month]:month:' \
    '(-l --limit)'{-l,--limit}'[limit]:limit:' \
    '--offset[offset]:offset:' \
    '--json[json]' \
    '--fr[fr]'
}

_atip_session_keepalive() {
  _arguments -s -S \
    '(-i --interval-minutes)'{-i,--interval-minutes}'[interval-minutes]:interval-minutes:'
}

_atip_session() {
  local state line
  typeset -A opt_args

  _arguments -C \
    '1:subcommand:(refresh keepalive)' \
    '*:: :->args'

  case $state in
    args)
      case $line[1] in
    refresh) _normal ;;
    keepalive) _atip_session_keepalive ;;
      esac
      ;;
  esac
}

_atip() {
  local state line
  typeset -A opt_args

  _arguments -C \
    '1:subcommand:(completion informal login logout orgs portal request search session)' \
    '*:: :->args'

  case $state in
    args)
      case $line[1] in
    completion) _atip_completion ;;
    informal) _atip_informal ;;
    login) _atip_login ;;
    logout) _normal ;;
    orgs) _atip_orgs ;;
    portal) _atip_portal ;;
    request) _atip_request ;;
    search) _atip_search ;;
    session) _atip_session ;;
      esac
      ;;
  esac
}

compdef _atip atip
